#ifndef BLE_KEYBOARD_MAIN_CONFIG_H
#define BLE_KEYBOARD_MAIN_CONFIG_H

#include <hal/gpio_types.h>

// General config
#define CONFIG_NAME_SIZE 21
#define CONFIG_DEVICE_NAME_SIZE 21
#define CONFIG_NOT_FOUND_INDEX 0xFF

// Version config
#define CONFIG_VERSION_MAJOR 1
#define CONFIG_VERSION_MINOR 0
#define CONFIG_VERSION_PATCH 0
#define CONFIG_VERSION_STORAGE_KEY "version"

// Buttons config
#define CONFIG_BUTTON_LOOP GPIO_NUM_4
#define CONFIG_BUTTON_PLAY GPIO_NUM_25
#define CONFIG_BUTTON_BACK GPIO_NUM_27
#define CONFIG_BUTTON_SPEED GPIO_NUM_26
#define CONFIG_BUTTON_FORWARD GPIO_NUM_32
#define CONFIG_BUTTON_LONG_PRESS_DURATION 1500
#define CONFIG_BUTTON_LONG_LONG_PRESS_DURATION 10000


#endif //BLE_KEYBOARD_MAIN_CONFIG_H
